---
# included file

- name: Mkdir a temp folder for uploading an updated conf files for jenkins
  file:
    state: directory
    path: /tmp/jenkins

- name: Copy updated default.conf file
  copy:
    src: "{{item}}"
    dest: "/tmp/jenkins"
  with_items:
    - jenkins-2.72-1.1.noarch.rpm
    - jenkins.io.key


- name: Jenkins RPM Key
  rpm_key:
    key: "/tmp/jenkins/jenkins-ci.org.key"
    validate_certs: "{{ jenkins2_rpm_key_validate_certs }}"
    state: present
  become: yes


- name: Jenkins Installation
  yum:
    name: "/tmp/jenkins/jenkins-2.72-1.1.noarch.rpm"
    disable_gpg_check: "{{ jenkins2_disable_gpg_check }}"
    state: present
  become: yes
